### ISSUE TITLE
[Integrations UI] Add remaining meshery integrations

### ISSUE THREAD

**Issue by Shivam-AfA** [meshery/meshery.io#1005]
### Description
[https://meshery.io/](url) website features only 80 integrations in contrast to the 150 integrations on the [https://layer5.io/](url) website.

### Expected Behavior
All the remaining integrations need to be added to the integrations section on meshery.io website.

## How to Implement

See https://github.com/meshery/meshery.io/issues/1005#issuecomment-1424666387

### Screenshots
**Meshery.io website**
![image](https://user-images.githubusercontent.com/88040318/217089047-d8cd203f-7c5c-4635-b9c8-177437b84b8f.png)

**Layer5 wesbite**
![image](https://user-images.githubusercontent.com/88040318/217089105-fcffdc14-f83c-4474-b279-f6ddc7dd03d3.png)

### Enviroment:
 - OS: Mac Linux Windows
 - Browser: Chrome Safari Firefox
 - Version: 
 - Device: Desktop Mobile

---
## Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by Savio629** [comment]
@Shivam-AfA So remaining 70 integrations should be added to meshery.io website?
I can take up the issue....

**Comment by leecalcote** [comment]
@Savio629 this needs to be done programmatically. The solution here has to do with GitHub Workflow logic. @asubedy will you investigate?

**Comment by Savio629** [comment]
Yeah it seems I just thought that I would have to copy the 70 integrations from meshery.io and add them in meshery.io. Sorry for directly hoping in, instead of exploring the issue a bit more from my side.

**Comment by gopivaibhav** [comment]
I am interested to work on this issue and I have gone through this issue in the CI call. So, can I get assigned to it?

**Comment by Shivam-AfA** [comment]
Sure @gopivaibhav. Do consider this:
>  this needs to be done programmatically (and not by manually adding the integrations. The solution here has to do with GitHub Workflow logic.

**Comment by asubedy** [comment]
Ok, these are where the issue present
1. The workflow [integration_updater](https://github.com/meshery/meshery/actions/workflows/integrations-updater.yml) is working perfectly fine, it updates the meshery repo as well as meshery repo with the required files or changes.
2. In the Meshery repository the workflow makes changes to the [data.json](https://github.com/meshery/meshery.io/blob/master/integrations/data.json) file and then commits it. And this file has the correct number of integrations, that is around 150.
3. So now the problem here is that the  current html file that is responsible for showing the integration [integration.html](https://github.com/meshery/meshery.io/blob/master/integrations/index.html) is using a the data source as a different js file as seen [here](https://github.com/meshery/meshery.io/blob/5a0bb9c567948c4a7c2426906a1b5d6e7dbb7f0c/integrations/index.html#L199). This file [data.js](https://github.com/meshery/meshery.io/blob/master/integrations/data.js) has hardcoded 80 integrations hence we see only 80 integrations on the website
4. So if we use the content from `data.json` file to show the integrations then this should solve the problem.

Few things to take note:
The content on data.json file is in such format
```
[{
      "name":"Fluid",
      "color":"../images/integration/fluid-color.svg",
      "white":"../images/integration/fluid-white.svg"},....]
   ```

So to render the integrations properly first the inverted commas on the keys that are "name","color" and "white" should be removed and the image link should not have the integration part so the image link will look like `../images/fluid-color.svg`

**Comment by Shivam-AfA** [comment]
@gopivaibhav any updates on this?

**Comment by gopivaibhav** [comment]
> @gopivaibhav any updates on this?

The issue is almost done but I guess I need to change the styling as I can't see all the 150 integrations without scrolling in the table format. Please do let me know if this is fine or I will try to change the styling of the page.
