### ISSUE TITLE
Menu Display Issue: Hamburger Icon visible and MENU button also visible at a time

### ISSUE THREAD

**Issue by shaikahmadnawaz** [meshery/meshery.io#1104]
#### Current State of the Meshery.io site

Hamburger Icon visible and MENU button also visible at a time in mobile view

![Screenshot (605)](https://user-images.githubusercontent.com/96189881/230103599-ab0008cd-e18a-45b5-ac84-b2a9f8008532.png)

#### Desired State of the Meshery.io site

Only the Hamburger icon must be visible in mobile view and MENU button must be invisible

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- 📚 See the [Contributing to Meshery.io Website](https://github.com/meshery/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](https://slack.meshery.io)

**Comment by randychilau** [comment]
Hi Shaik, 

Good day! 

Not sure if you have already resolved this issue, but [here is some information ](https://github.com/meshery/meshery.io/issues/1035#issuecomment-1485967702) that might be helpful.

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
> Hi Shaik, 
> 
> Good day! 
> 
> Not sure if you have already resolved this issue, but [here is some information ](https://github.com/meshery/meshery.io/issues/1035#issuecomment-1485967702) that might be helpful.
> 
> Cheers,
> Randy

Great, I'm new to this, just give me clarity, shall I solve this issue or close it.

**Comment by randychilau** [comment]
Hi Shaik,

Apologies, I am also very new to this, and did not mean to cause any confusion. I just wanted to share the information with whomever was assigned the issue.

Please continue solving the issue and sorry again for any confusion caused.

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
> Hi Shaik,
> 
> Apologies, I am also very new to this, and did not mean to cause any confusion. I just wanted to share the information with whomever was assigned the issue.
> 
> Please continue solving the issue and sorry again for any confusion caused.
> 
> Cheers,
> Randy
> 

Sorry for the misunderstanding, I think you are trying to help me, now I got the point, thanks for sharing the resource, definitely I will take it as a reference you shared.

Thank you 😊

**Comment by shaikahmadnawaz** [comment]
In my localhost it is absolutely fine, but why both Icon and MENU text are visible in [meshery.io](https://meshery.io/), reply please @Chadha93 @randychilau 

![Screenshot (607)](https://user-images.githubusercontent.com/96189881/230431671-f23d50f3-0dea-447e-87c9-ee53fc4d42a2.png)

**Comment by shaikahmadnawaz** [comment]
Thanks a lot @randychilau, with the help of you I did it ❤️

**Comment by randychilau** [comment]
Hi Shaik, 

Congratulations on your submission, nice work!

One small thing you want to consider is that the code should also load the stellarnav file when the `jekyll.environment` is "development" (e.g. an` else` option) since that is the default environment for folks like yourself making changes to the code.

If there is no accommodation for the `jekyll.environment` being "development", then the stellarnav file will not load and the hamburger menu will not appear when they load the site in the browser.

One way to check that your fix is showing up in both environments is to: 

- load your changes in the development environment using the command `make site`

and then 

- load your changes in the production environment using the command `JEKYLL_ENV=production bundle exec jekyll build`

and your changes to the hamburger menu should appear in both.

Hope that helps!

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
Check the PR once @randychilau, is everything okay now

**Comment by randychilau** [comment]
Hi Shaik,

Thanks for your message. 

I took a look at the PR and checked the updated [preview](https://deploy-preview-1107--mesheryio-preview.netlify.app/), nice job!

It looks like it is handling both environments now, and it is showing up in the [preview](https://deploy-preview-1107--mesheryio-preview.netlify.app/) now:

![image](https://user-images.githubusercontent.com/90356410/230513319-50630237-e4ff-4acc-947f-a41784b2ace9.png)


I think the reason it wasn't showing in the preview before is because it seems the netlify deploy preview also uses "development" environment (since it does not specify "production" environment), at least that is what is seems like from the [processing logs](https://app.netlify.com/sites/mesheryio-preview/deploys/642f5715f4dfe0000837690b):

![image](https://user-images.githubusercontent.com/90356410/230513814-c0abd65f-259a-4806-833e-933d5b5a9e8c.png)


Anyway, looks good!

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
Thanks @randychilau, for guiding in this entire process, by the how you are familiar with all this stuff, I am MERN stack developer, that's I struggling with Jekyll.

**Comment by randychilau** [comment]
HI Shaik,

Glad to help and congrats again on your PR! 

Hopefully they will review it again soon with the recent updates and give you more feedback.

Hah, every day on this coding journey is a "struggle" / "challenge" / "learning experience" / "opportunity", so it can nice to collaborate with others along the way (I am still learning that).

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
Hoping that they will review it again and this is my first open source contribution if they merged, by the can we connect? Eg: LinkedIn or Twitter

**Comment by randychilau** [comment]
Hi Shaik,

One option might be to add a comment on the PR that you have updated the code and include a screenshot of the deploy preview link in mobile mode showing the hamburger menu.

Also thanks for asking to connect, I am still rebuilding my LinkedIn, but will be happy to connect when it is done. I am on the Meshery slack, I will send you a wave!

Cheers,
Randy

**Comment by randychilau** [comment]
Hi Shaik,

Nice, it is good to get comments and feedback on your work, everyone is helping each other on this coding journey.

Let's take a look at each of the comments:

> while clicking on hamburger icon the complete box shouldn't be blue.

Since you are already working on the feature, you are being asked to make additional changes not included in the original issue which is good since it is an opportunity to work on more stuff and learn more. Plus as stated:

> these changes are required for better experience

Note sure if you have already handled this, but seems like you can modify the stellarnav CSS files in the appropriate section to style the dropdown. 

`css/stellarnav.css`

It sounds like they are letting you choose how to style it, so one option may be to choose a similar color to the mobile site background, but enough difference for the dropdown menu stand out.

----

> when the dropdown menu is open we should display a cross icon instead of hamburger icon with some animation. you can see https://meshery.io/ for reference.

This will require more work, as you will have to find the portions of code and css in the meshery.io site to copy the open/close effect of the hamburger menu icon, and then put them into the appropriate files. You should be able to find what you need in this folder:

meshery/src/sections/General/Navigation

If you feel like this is a separate task that requires a lot of time and work, maybe you can ask them to do this task as a separate PR? 

----

![image](https://user-images.githubusercontent.com/90356410/230647326-1b80ff49-9f78-4252-86ba-6066f0babc3f.png)

regarding this comment, I couldn't find a place where the min.js version of the file is being autogenerated, but I am still a beginner.

What you can do is after you update the stellarnav js file to your liking, you can convert the code to minified versions using online tools (e.g. https://www.toptal.com/developers/javascript-minifier) and then update the min.js file. Then you can update the if/else statement to use the minified version for production (since it saves on loading time as smaller files). 

----

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
> Hi Shaik,
> 
> Nice, it is good to get comments and feedback on your work, everyone is helping each other on this coding journey.
> 
> Let's take a look at each of the comments:
> 
> > while clicking on hamburger icon the complete box shouldn't be blue.
> 
> Since you are already working on the feature, you are being asked to make additional changes not included in the original issue which is good since it is an opportunity to work on more stuff and learn more. Plus as stated:
> 
> > these changes are required for better experience
> 
> Note sure if you have already handled this, but seems like you can modify the stellarnav CSS files in the appropriate section to style the dropdown. 
> 
> `css/stellarnav.css`
> 
> It sounds like they are letting you choose how to style it, so one option may be to choose a similar color to the mobile site background, but enough difference for the dropdown menu stand out.
> 
> ----
> 
> > when the dropdown menu is open we should display a cross icon instead of hamburger icon with some animation. you can see https://meshery.io/ for reference.
> 
> This will require more work, as you will have to find the portions of code and css in the meshery.io site to copy the open/close effect of the hamburger menu icon, and then put them into the appropriate files. You should be able to find what you need in this folder:
> 
> meshery/src/sections/General/Navigation
> 
> If you feel like this is a separate task that requires a lot of time and work, maybe you can ask them to do this task as a separate PR? 
> 
> ----
> 
> ![image](https://user-images.githubusercontent.com/90356410/230647326-1b80ff49-9f78-4252-86ba-6066f0babc3f.png)
> 
> regarding this comment, I couldn't find a place where the min.js version of the file is being autogenerated, but I am still a beginner.
> 
> What you can do is after you update the stellarnav js file to your liking, you can convert the code to minified versions using online tools (e.g. https://www.toptal.com/developers/javascript-minifier) and then update the min.js file. Then you can update the if/else statement to use the minified version for production (since it saves on loading time as smaller files). 
> 
> ----
> 
> Cheers,
> Randy

Okay, I will work on this based on your suggestions, Thank you Randy 😊

**Comment by randychilau** [comment]
Hi Shaik,

Good luck!

Also, regarding the hamburger menu animation, there are many different solutions available online:

[example 1](https://codepen.io/designcouch/pen/ExvwPY)
[example 2](https://javascript.plainenglish.io/animated-hamburger-menu-in-vanilla-javascript-79bd97da00b9)

so while one method may be to try replicating the code used on Meshery.io, feel free to explore and research other methods that you may like better for the Meshery.io codebase.

Cheers,
Randy

**Comment by shaikahmadnawaz** [comment]
> Hi Shaik,
> 
> Good luck!
> 
> Also, regarding the hamburger menu animation, there are many different solutions available online:
> 
> [example 1](https://codepen.io/designcouch/pen/ExvwPY) [example 2](https://javascript.plainenglish.io/animated-hamburger-menu-in-vanilla-javascript-79bd97da00b9)
> 
> so while one method may be to try replicating the code used on Meshery.io, feel free to explore and research other methods that you may like better for the Meshery.io codebase.
> 
> Cheers, Randy

Okay @randychilau, thanks for sharing the references 👍

**Comment by Ghat0tkach** [comment]
@karangit @vishalvivekm @HarshDobariya79 , This issue has been completed in PR #1130 . We can close this now

**Comment by iArchitSharma** [comment]
> @KaranGit @vishalvivekm @HarshDobariya79 , This issue has been completed in PR #1130 . We can close this now

Closing this since it's already fixed in [#1130](https://github.com/meshery/meshery.io/pull/1130)
