### ISSUE TITLE
No dark mode for twitter Widget

### ISSUE THREAD

**Issue by ranjanmangla1** [meshery/meshery.io#1242]
#### Current Behavior
There is no dark mode for twitter timeline in footer at meshery.io

#### Desired Behavior
The twitter timeline should also change with dark mode of site

#### Purposed Solution
The theme of widget can be changed according to the guidelines given here:
https://developer.twitter.com/en/docs/twitter-for-websites/embedded-tweets/guides/cms-best-practices 

#### Screenshots/Logs
![image](https://github.com/meshery/meshery/assets/93506927/581ad0bd-45fb-4103-8fd8-f3549c9a7c35)

**Comment by thisiskaransgit** [comment]
@ranjanmangla1,  ⚠️ Fair Warning, Please refrain from repeatedly raising the same issue #1213, in meshery/meshery as [#7920](https://github.com/meshery/meshery/issues/7920). It is important for us to maintain a clear and organized issue tracker so that all contributors can easily follow the progress of each reported problem. If you think that the raised issue might have been overlooked, (which happens rarely), We encourage you to share it on our public Slack channels and ask for an assignment.

As for the raised concern, you can go ahead and provide a solution for this. Also, Show your work at the website meeting which happens on Mondays, to know more about it go to [layer5.io/calendar](https://layer5.io/calendar)

**Comment by ranjanmangla1** [comment]
sorry @thisiskaransgit for the mistake I have made. It was unintentional, i forgot to close the issue #7920 at meshery/meshery, because to my knowledge it should have been opened here, not at meshery/meshery. Once again, very sorry, I will make sure this do not happen again

**Comment by thisiskaransgit** [comment]
@ranjanmangla1, No worries about the mistake! We appreciate your contributions to the project. Keep up the great work and make sure to follow our guidelines moving forward. If you ever need any assistance or clarification regarding our guidelines or any aspect of the project, please don't hesitate to reach out. We are here to support each other!
Thank you again for being a part of this community!

**Comment by thisiskaransgit** [comment]
Thanks for the PR, but since the widget is not working, due to twitter's new open-access policy, we'll be closing this issue. Thank you for your efforts though.
