### ISSUE TITLE
[UI] The Catalog Description not looks good 

### ISSUE THREAD

**Issue by dhamkirti21** [meshery/meshery.io#1432]
### Current Behavior

Certainly, addressing the concerns about the Catalog Description Page and its formatting in a best manner is important to encourage improvements. 

### Desired Behavior

Maybe we can format the description in a good manner and fix formating issue

### Screenshots/Logs

![image](https://github.com/meshery/meshery.io/assets/78336507/c182f116-7522-4a00-9186-1f606144b82e)

**Comment by shiivamtaneja** [comment]
Hi can i work on this?

**Comment by dhamkirti21** [comment]
@shiivamtaneja  you can work on this.

**Comment by shiivamtaneja** [comment]
hey @leecalcote  can you please assign me this issue.

**Comment by Akshun-01** [comment]
Hi @shiivamtaneja, I think if you are working on the UI of this page, this tag with "deployment" would be better in white similar to the rest of the page, as all the call-to-action buttons follow that trend.
![image](https://github.com/meshery/meshery.io/assets/93793691/d4997292-9f9d-4af9-aa1b-6e9bbcc5e955)

@leecalcote  @ritiksaxena124 what do you suggest?

**Comment by shiivamtaneja** [comment]
Hey @Akshun-01 I haven't yet started working on this issue; I'm still awaiting confirmation from the maintainers to assign the issue to me so that i can start the work. 

Yeah I also think the "development" tag could be updated like it is in the ss below. That way, it will fit the theme better as a whole. 
![image](https://github.com/meshery/meshery.io/assets/79853285/8b248f43-b078-4117-af38-57e2f210a7f0)

**Comment by Ghat0tkach** [comment]
Actually these are published through a github action from meshery cloud . Fixing directly from this repo wont solve the problem .😅

**Comment by shiivamtaneja** [comment]
So what do you suggest? @Ghat0tkach

**Comment by sudhanshutech** [comment]
This is not a appropriate issue, this thing should be resolved from github work flow. Lets close this
