### ISSUE TITLE
Update the small typo

### ISSUE THREAD

**Issue by lavakush07** [meshery/meshery.io#833]
#### Current State

- Correct the word **compatibilty** . While I am reading the docs I came to this one.
![image](https://user-images.githubusercontent.com/70131581/188363695-8d8f7105-173f-4127-b06b-6f3f6f16ec73.png)

#### Desired State
 
- Change it to **compatibility** 
- A beginner friendly issue. Any new comer can take this one 
---

#### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/build-and-release)
- 🎨 Wireframes and designs for Meshery UI in [Figma](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](https://discuss.layer5.io) and [Community Slack](http://slack.layer5.io)

**Comment by sam1code** [comment]
Hii @lavakush07 can you please assign me this one please I'm a biginner to mershy.

**Comment by leecalcote** [comment]
More tough love, @sam1code. No, an issue to fix a typo will not be assigned to someone who includes typos in the request to fix typos.

Again, this message follows on our private conversations and is sent from a place of a desire to build you up through tough love (because it isn't working otherwise).

Find another issue, please, @sam1code.

**Comment by sam1code** [comment]
Yes I also will not count this...
